In [6]:
my_list = [1, 2, 3, 4, 5]
print(my_list)


[1, 2, 3, 4, 5]


In [7]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)


[1 2 3 4 5]


In [8]:
my_list = [1, 2, 3, 4, 5]
print(type(my_list))


<class 'list'>


In [9]:
my_array = np.array([1, 2, 3, 4, 5])
print(type(my_array))


<class 'numpy.ndarray'>


In [10]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 * array2
print(result)
result = array1 / array2
print(result)
result = array1 ** array2
print(result)
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.add(array1, array2)
text = "Addition of Two: " + str(result)
print(text)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
Addition of Two: [5 7 9]


In [12]:
import numpy as np

a = np.sin(90)
b = np.log(1)
c = np.log2(2)
d = np.exp(0)

print("np.sin(90) =", round(a))
print("np.log(1) =", b)
print("np.log2(2) =", c)
print("np.exp(0) =", d)

np.sin(90) = 1
np.log(1) = 0.0
np.log2(2) = 1.0
np.exp(0) = 1.0
